title: Luverie
tagline: Security Research & AD Mindmap Project
description: Chia sẻ kiến thức Active Directory & CTF cho cộng đồng Việt Nam.

url: "https://Luv3rie.github.io"
baseurl: ""

lang: vi-VN
timezone: Asia/Ho_Chi_Minh

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
minima:
  skin: dark

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    disable: false
